### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Elshid** [ycaseau/CLAIRE4#4]
The license of CLAIRE is found in the main README-document, which is generally speaking a bad idea. As previous CLAIRE iterations are licensed under a permissive license, I recommend the Apache license.

**Comment by ycaseau** [comment]
Hello Mirko,

it's been a while since I last looked at the issue :).
My previous understanding was that there is a difference between:
- the copyright, which mostly is there to prevent someone from blocking me to use CLAIRE
- the license to use, which is granted to everyone - use and redistribution - in the README.

I'll be happy to switch to something more modern/liberal. I tried to look into GPL but I got confused and did not have the time to pursue.
If you have a reference about how to use the Apache licence (i.e. what to put where, README, header, ...), please let me know,

Best regards,

Yves

**Comment by Elshid** [comment]
I agree with you, the situation is quite complicated.

As you are not using third party code (as far as I see), the thing is quite easy for you. Generally speaking, most developers add a LICENSE file to the code. The text for the Apache licence can be found here: https://apache.org/licenses/LICENSE-2.0.txt. It is a bit longer than e.g., the BSD-licenses, but it protects users and developers from the misuse of patent claims, as it grants everyone the right to use a patent if the code is patented.
However, unlike the GPL, it allows the CLAIRE compiler to be added to a proprietary product, like another CLAIRE compiler with some added features. No matter if you use the GPL or Apache, you can still develop and run proprietary programs with the help of the interpreter. If you are considering to use the GPL, things might get a bit tricky for the compiler part of CLAIRE, as AFAIK, compilers insert parts of their own bytecode into the produced binary. Therefore, you need to add a so-called compiler exception, so you can compile non-free code with the CLAIRE compiler. This was done for the GCC. An example of this exception (that needs to be adapted for CLAIRE is here: https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html)

I would like to add that I am no lawyer and have no experience in developing compilers, I am just a computer science student.

I hope this is helpful. If you need more help concerning the GPL, the legal team of the FSF is quite helpful. See here: https://www.fsf.org/licensing/
I am also happy to help.

**Comment by ycaseau** [comment]
Many thanks for the help !
I have added a LICENCE.txt to the repository, under the Apache licence.
This states much more nicely the rights to use and redistribute.

**Comment by Elshid** [comment]
I think that everything is fine now.
I'll close the issue.
